[package]
name = "hyperbuild-ruby"
publish = false
version = "0.1.10"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[lib]
name = "hyperbuild_ruby_lib"
crate-type = ["cdylib"]

[dependencies]
hyperbuild = "0.1.10"
rutie = "0.7.0"
