[package]
name = "hyperbuild-ruby"
publish = false
version = "0.2.4"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[lib]
name = "hyperbuild_ruby_lib"
crate-type = ["cdylib"]

[dependencies]
hyperbuild = { path = "..", features = ["js-esbuild"] }
rutie = "0.7.0"
