[package]
name = "minify-html"
description = "Uncompromisingly fast and smart HTML + JS minifier"
license = "MIT"
homepage = "https://github.com/wilsonzlin/minify-html"
readme = "README.md"
keywords = ["html", "compress", "minifier", "minify", "minification"]
categories = ["compression", "command-line-utilities", "development-tools::build-utils", "web-programming"]
repository = "https://github.com/wilsonzlin/minify-html.git"
version = "0.2.6"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
js-esbuild = ["esbuild-rs"]

[dependencies]
esbuild-rs = { version = "0.0.5", optional = true }
lazy_static = "1.4.0"
memchr = "2.3.3"

[profile.release]
panic = 'abort'
