[package]
name = "hyperbuild"
description = "Fast one-pass in-place HTML minifier written in Rust with context-aware whitespace handling"
license = "MIT"
homepage = "https://github.com/wilsonzlin/hyperbuild"
readme = "README.md"
keywords = ["html", "compress", "minifier", "minify", "minification"]
categories = ["compression", "command-line-utilities", "development-tools::build-utils", "web-programming"]
repository = "https://github.com/wilsonzlin/hyperbuild.git"
version = "0.1.8"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"
include = ["/src/**/*", "/Cargo.toml", "/LICENSE", "/README.md"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
lazy_static = "1.4.0"
regex = "1.3.9"
memchr = "2.3.3"

[profile.release]
panic = 'abort'
