[package]
publish = false
name = "minify-html-cli"
version = "0.3.4"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[dependencies]
minify-html = { path = "..", features = ["js-esbuild"] }
structopt = "0.3"
