[package]
name = "hyperbuild-cli"
publish = false
version = "0.2.4"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[dependencies]
hyperbuild = { path = "..", features = ["js-esbuild"] }
structopt = "0.3.5"
