[package]
name = "minhtml"
description = "[CLI] Extremely fast and smart HTML + JS + CSS minifier"
version = "0.12.0"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[dependencies]
minify-html = { path = "../minify-html" }
rayon = "1.5"
structopt = "0.3"
