[package]
name = "hyperbuild-java"
version = "0.0.15"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[dependencies]
hyperbuild = "0.0.15"
jni = "0.14.0"

[lib]
crate-type = ["cdylib"]
path = "src/main/rust/lib.rs"
