[package]
publish = false
name = "minify-html-java"
version = "0.17.1"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[dependencies]
minify-html = { path = "../minify-html" }
jni = "0.21"

[lib]
crate-type = ["cdylib"]
path = "src/main/rust/lib.rs"
