[package]
publish = false
name = "minify-html-ruby"
version = "0.11.2"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[lib]
name = "minify_html_ruby_lib"
crate-type = ["cdylib"]

[dependencies]
minify-html = { path = "../../../minify-html" }
magnus = "0.6"
