[package]
name = "hyperbuild-python"
publish = false
version = "0.0.33"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[lib]
name = "hyperbuild_python_lib"
crate-type = ["cdylib"]

[dependencies]
hyperbuild = "0.0.33"
[dependencies.pyo3]
version = "0.9.0-alpha.1"
features = ["extension-module"]
