[package]
name = "hyperbuild-python"
publish = false
version = "0.2.0"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[lib]
name = "hyperbuild_python_lib"
crate-type = ["cdylib"]

[dependencies]
hyperbuild = "0.2.0"
[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]
