[package]
name = "hyperbuild-python"
publish = false
version = "0.2.3"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[lib]
name = "hyperbuild_python_lib"
crate-type = ["cdylib"]

[dependencies]
hyperbuild = { path = "..", features = ["js-esbuild"] }
[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]
