[package]
name = "minify-html-bench"
publish = false
version = "0.0.1"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[dependencies]
minify-html = { path = "../../../minify-html" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
