[package]
name = "hyperbuild-nodejs"
publish = false
version = "0.2.3"
authors = ["Wilson Lin <code@wilsonl.in>"]
license = "MIT"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]
edition = "2018"

[lib]
name = "hyperbuild_nodejs_lib"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.4.0"

[dependencies]
hyperbuild = "0.2.3"
neon = "0.4.0"
