name: Build and publish Deno package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    # https://jsr.io/docs/publishing-packages#publishing-from-github-actions
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v1

      - name: Get version
        id: version
        shell: bash
        run: echo ::set-output name=VERSION::"$([[ "$GITHUB_REF" == refs/tags/v* ]] && echo ${GITHUB_REF#refs/tags/v} || echo '0.0.0')"

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true

      - name: Install wasm-pack
        working-directory: ./minify-html-wasm
        shell: bash
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build native module
        working-directory: ./minify-html-wasm
        shell: bash
        run: TARGET=web ./build

      - name: Publish to JSR
        working-directory: ./minify-html-wasm/pkg
        run: npx jsr publish
